### ISSUE TITLE
Types could not be resolved when respecting package.json "exports".

### ISSUE THREAD

**Issue by thisislvca** [capricorncd/zx-sml#13]
Hey! Just found this types bug in the repo. I don't know if this has been already fixed and the `image-process` package (also by @capricorncd ) hasn't been updated to the latest version, but I figured I'd put it here since it's related to this package.

```bash
./node_modules/image-process/packages/core/src/handle-image-file.ts:21:8

Type error: Could not find a declaration file for module 'zx-sml'. '/home/luca/Documents/dev/inpilot/node_modules/zx-sml/dist/zx-sml.es.js' implicitly has an 'any' type.
  There are types at '/home/luca/Documents/dev/inpilot/node_modules/zx-sml/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'zx-sml' library may need to update its package.json or typings.

  19 |   createBlobURL,
  20 |   base64ToBlob,
> 21 | } from 'zx-sml'
     |        ^
  22 | import { DEFAULT_OPTIONS } from './options'
  23 |
  24 | const base64Reg = /^data:(.+?);base64/
error: script "build" exited with code 1 (SIGHUP)
```

The problem is present both with latest current and latest LTS versions of node (`v21.2.0` and `v20.10.0 LTS`).

[An issue about this has been opened and closed in the typescript repo](https://github.com/microsoft/TypeScript/issues/52363), and there's a solution outlined. That solution requires the package manager to update its exports ideally, so here I am opening the issue :)

I don't know how to fix it myself as I have virtually zero experience creating node packages...

To recreate the issue just create a Next.js typescript project and use the package `image-process` anywhere. Error occurs in `npm run build` when checking types validity.

**Comment by capricorncd** [comment]
Can you tell me which version of image-process you are using?
or update image-process to latest version 4.3.3 
https://github.com/capricorncd/image-process-tools
